version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U root' ]
      interval: 5s

  back:
    image: aperushin/sky_hw26:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 5000:5000

    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_started

  migrations:
    build:
      context: .
      dockerfile: mig.Dockerfile
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
    depends_on:
      db:
        condition: service_healthy