name: build and deploy
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t aperushin/sky_hw26:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_UNAME }} --password-stdin
      - name: docker push
        run: docker push aperushin/sky_hw26:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-latest
      steps:
        - name: clone code
          uses: actions/checkout@v2
        - name: render configs
          run: |
            mkdir deploy
            cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
        - name: copy files to server
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_UNAME }}
            password: ${{ secrets.SSH_PASS }}
            source: "deploy/docker-compose.yaml"
            target: "flask_app_ci"
            strip_components: 1
